# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
version: 1
name: fedora-silverblue-surface
description: Ein angepasstes Fedora Silverblue Image fuer Microsoft Surface Geraete mit integriertem linux-surface Kernel.

base-image: ghcr.io/blue-build/base-images/fedora-silverblue
image-version: latest

modules:
  # Treiber und linux-surface Repositories einbinden sowie Kernel austauschen
  - type: dnf
    repos:
      files:
        - https://pkg.surfacelinux.com/fedora/linux-surface.repo
    remove:
      packages:
        - kernel
        - kernel-core
        - kernel-modules
        - kernel-modules-extra
    install:
      packages:
        - kernel-surface
        - kernel-surface-devel
        - iptsd                   # Wichtig fuer Touchscreen-Unterstuetzung
        - libwacom-surface        # Angepasste Tablet-Konfigurationen
        - surface-secureboot      # Importiert MOK-Keys fuer Secure Boot beim ersten Start

  # Den iptsd Touchscreen-Daemon beim Systemstart aktivieren
  - type: systemd
    system:
      enabled:
        - iptsd.service
